---
#
# Automysql Backup: tasks file for automysqlbackup
#
# The Apt version is 2.5 - the latest version is 3
#  Creates the following folders
#
#  ./etc/automysqlbackup
#  ./etc/default/automysqlbackup - the default config
#  ./etc/cron.daily/automysqlbackup - cron job
#  ./usr/share/doc/automysqlbackup/ - readme
#  ./usr/sbin/automysqlbackup - the script itself
#  ./var/lib/automysqlbackup

- name: Package | Automysqlbackup install
  apt:
    name: automysqlbackup
    state: installed
  become: true
  tags:
    - automysqlbackup

- name: Package | Automysqlbackup set backup cfg
  template:
    src: automysqlbackup_v2.conf.j2
    dest: /etc/default/automysqlbackup
    backup: yes
  tags:
   - automysqlbackup

# created by package manager
# - name: Package | Automysqlbackup daily cronjob for backup
#   cron:
#     name: "Automysqlbackup - Backup DB"
#     hour: "{{ automysqlbackup_cron_hour }}"
#     minute: "{{ automysqlbackup_cron_minute }}"
#     job: "{{ automysqlbackup_binpath }} > /dev/null"
#   tags:
#     - automysqlbackup